version: '3.5'
services:
  ca:
    image: edgd1er/simple_cfssl
    build:
      context: build
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - "8888/tcp"
    ports:
      - "10888:8888/tcp"
      - "10889:8889/tcp"
    volumes:
      - ./DATA:/DATA
    environment:
      TZ: Europe/Paris
      CA_CN_name: "CA_name"
      CA_KEY_ALGO: "rsa"
      CA_KEY_SIZE: 2048
      CA_Country: "FR"
      CA_Location: "Paris"
      CA_Organisation: "CA Org"
      CA_State: "N/A"
      CAI1_Name: "production"
      CAI2_Name: "development"
      #need step 2: 1 for CA service / 1 for OCSP service
      CAI1_PORT: 8888
      CAI2_PORT: 8890
    labels:
      com.centurylinklabs.watchtower.enable: "false"
      traefik.enable: "false"
      traefik.http.routers.plex.rule: "Host(`ca.mission.lan`)"
      traefik.http.routers.plex.entrypoints: "https"
      traefik.http.routers.plex.tls: "true"
      # Redirect to https
      #traefik.http.middlewares.https.redirectscheme.scheme: "https"
      #traefik.http.middlewares.https.redirectscheme.permanent: "true"
      #traefik.http.routers.plex.middlewares: "https"
